os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=$PATH:flutter/bin/
- flutter doctor
- flutter pub global activate webdev
- flutter pub global activate peanut
script:
- flutter pub upgrade
- flutter pub run test -p chrome
- peanut
- git push origin --set-upstream gh-pages
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.pub-cache
