os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=$PATH:flutter/bin/
- flutter doctor
- flutter pub global activate webdev
- flutter pub global activate peanut
script:
- flutter pub upgrade
- flutter pub run test -p chrome
- flutter pub run build_runner peanut
after_success:
- bash <(curl -s https://codecov.io/bash)
- git checkout gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
cache:
  directories:
  - $HOME/.pub-cache
