name: overlay_support
description: proivder support for overlay, easy to build toast and internal notification
version: 0.3.0
author: YangBin <yangbinyhbn@gmail.com>
homepage: https://github.com/boyan01/overlay_support

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  async: ^2.2.0

dev_dependencies:
  flutter_web_test: any
  test: ^1.3.0
  path: ^1.6.2
  quiver: ^2.0.1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test